package com.ecgproject.settings.domain;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_id
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_status
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    private Integer staffStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_describe
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    private String staffDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_work
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    private Integer staffWork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_name
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    private String staffName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_id
     *
     * @return the value of staff.staff_id
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_id
     *
     * @param staffId the value for staff.staff_id
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_status
     *
     * @return the value of staff.staff_status
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    public Integer getStaffStatus() {
        return staffStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_status
     *
     * @param staffStatus the value for staff.staff_status
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    public void setStaffStatus(Integer staffStatus) {
        this.staffStatus = staffStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_describe
     *
     * @return the value of staff.staff_describe
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    public String getStaffDescribe() {
        return staffDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_describe
     *
     * @param staffDescribe the value for staff.staff_describe
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    public void setStaffDescribe(String staffDescribe) {
        this.staffDescribe = staffDescribe == null ? null : staffDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_work
     *
     * @return the value of staff.staff_work
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    public Integer getStaffWork() {
        return staffWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_work
     *
     * @param staffWork the value for staff.staff_work
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    public void setStaffWork(Integer staffWork) {
        this.staffWork = staffWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_name
     *
     * @return the value of staff.staff_name
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_name
     *
     * @param staffName the value for staff.staff_name
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }
}