package com.ecgproject.settings.domain;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_id
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_status
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    private String staffStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_describe
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    private String staffDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_work
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    private String staffWork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_name
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    private String staffName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_id
     *
     * @return the value of staff.staff_id
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_id
     *
     * @param staffId the value for staff.staff_id
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_status
     *
     * @return the value of staff.staff_status
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    public String getStaffStatus() {
        return staffStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_status
     *
     * @param staffStatus the value for staff.staff_status
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    public void setStaffStatus(String staffStatus) {
        this.staffStatus = staffStatus == null ? null : staffStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_describe
     *
     * @return the value of staff.staff_describe
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    public String getStaffDescribe() {
        return staffDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_describe
     *
     * @param staffDescribe the value for staff.staff_describe
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    public void setStaffDescribe(String staffDescribe) {
        this.staffDescribe = staffDescribe == null ? null : staffDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_work
     *
     * @return the value of staff.staff_work
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    public String getStaffWork() {
        return staffWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_work
     *
     * @param staffWork the value for staff.staff_work
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    public void setStaffWork(String staffWork) {
        this.staffWork = staffWork == null ? null : staffWork.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_name
     *
     * @return the value of staff.staff_name
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_name
     *
     * @param staffName the value for staff.staff_name
     *
     * @mbggenerated Mon May 02 16:53:33 CST 2022
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }


}