package com.ecgproject.settings.mapper;

import com.ecgproject.settings.domain.Staff;

public interface StaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    int deleteByPrimaryKey(String staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    int insert(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    int insertSelective(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    Staff selectByPrimaryKey(String staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    int updateByPrimaryKeySelective(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Thu Apr 21 11:16:54 CST 2022
     */
    int updateByPrimaryKey(Staff record);

    /**
     * 根据工号查询是否已经注册
     */
    Staff selectById(String userId);

    /**
     * 更新注册状态
     */
    int updateStatusById(String staffId);
}